### ISSUE TITLE
Skibidi-Boom: Blast Through Critical Performance Bottleneck in Data Pipeline 🚀💥

### ISSUE THREAD

**Issue by Lixczyy** [Lixczyy/SoulsoftheReborne#8]
![image](https://github.com/user-attachments/assets/38b23e64-26e7-496a-b598-6d27d61c44bc)
![image](https://github.com/user-attachments/assets/e871345a-5f7f-4cdd-b2f5-efec91ecf6fa)
![image](https://github.com/user-attachments/assets/ed37e094-b973-4415-862e-30c819f594a0)

**Comment by Aer0Scar** [comment]
![image](https://github.com/user-attachments/assets/b3010a3b-35d7-4fcb-99db-8ad28947478a)
fixed
